app/__init__.py
from flask import Flask
from config import Config

def create_app(class_config=Config):
    app = Flask(__name__)
    app.config.from_object(class_config)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes 

app/main/routes.py
from flask import Flask, render_template, redirect, url_for, flash
from app.main import bp


@bp.route('/')
def index():
    books = [
        {
            'title': 'The River War',
            'author': 'Winston Spencer Churchill',
            'pages': 350
        },
        {
            'title': 'FIVE WEEKS IN A BALLOON',
            'author': 'Jules Verne',
            'pages': 300
        }
    ]
    return render_template('index.html', title='Home', books=books)



@bp.route('/about')
def about():
    user = {
        'author': 'max',
        'email': 'max@example.com',
        'info': 'About Page'
    }
    return render_template('about.html', title='About', user=user)

app/templates/about.html
{% extends "base.html" %}
{% block content %}

<h1>About Page</h1>

<table>
    <tbody>
        <tr>
            <td>Author</td>
            <td>{{user.author}}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{user.email}}</td>
        </tr>
        <tr>
            <td>Info</td>
            <td>{{user.info}}</td>
        </tr>
    </tbody>

</table>


{% endblock content %}

app/templates/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% if title %}
        <title>{{title}}| Codelogs.net</title>
    {% else %}
        <title>Codelogs.net</title>
    {% endif %}
</head>
<body>

    <a href="{{url_for('main.index') }}">Codelogs.net</a>
    <a href="{{url_for('main.about')}}">About</a>
    <a href="{{ url_for('auth.login') }}">login</a>

    <div style="padding: 20px;">
        {% if get_flashed_messages() %}
            {% for message in get_flashed_messages() %}
                <p>{{message}}</p>
            {% endfor %}
        {% endif %}
    </div>
    {% block content %}{% endblock content %}

</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}

<h1>Books</h1>
{% for book in books %}
    <div style="padding: 20px;">
        <p>Title: {{book.title}}</p>
        <p>Author: {{book.author}}</p>
        <p>Pages: {{book.pages}}</p>
    </div>
{% endfor %}
{% endblock content %}